# Generated by Django 5.1.3 on 2024-11-09 05:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("website", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="record",
            name="address",
            field=models.CharField(default="default address", max_length=255),
        ),
    ]
